# Generated by Django 4.2.1 on 2023-09-22 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='pago_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagoagua',
            name='mes',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoagua',
            name='pago_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
